# publishes joint data to /joint_states
dsr_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# velocity mode controller
dsr_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  publish_rate: 100


# Velocity trajectory controller
dsr_joint_velocity_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  publish_rate: 100
  gains:
    joint1:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
    joint2:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
    joint3:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
    joint4:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
    joint5:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
    joint6:
      p: 1.0
      d: 0
      i: 0
      i_clamp: 0
  velocity_ff:
      joint_1: 1.0
      joint_2: 1.0
      joint_3: 1.0
      joint_4: 1.0
      joint_5: 1.0
  stop_trajectory_duration: 0
  constraints:
    joint1:
      trajectory: 0.1
      goal: 0.01
    joint2:
      trajectory: 0.1
      goal: 0.01
    joint3:
      trajectory: 0.1
      goal: 0.01
    joint4:
      trajectory: 0.1
      goal: 0.01
    joint5:
      trajectory: 0.1
      goal: 0.01
    joint6:
      trajectory: 0.1
      goal: 0.01
